const items = [
  {
    key: "1",
    id: 1,
    title: "Main",
    feeds: [2, 4],
    coords: [],
    subItems: [
      {
        key: "6",
        id: "1A",
        title: "Step A",
        feeds: [2, 4],
        coords: [],
        subItems: [],
      },
      {
        key: "7",
        id: "1B",
        title: "Step B",
        feeds: [2, 4],
        coords: [],
        subItems: [],
      },
      {
        key: "8",
        id: "1C",
        title: "Step C",
        feeds: [2, 4],
        coords: [],
        subItems: [],
      },
      {
        key: "9",
        id: "1D",
        title: "Step D",
        feeds: [2, 4],
        coords: [],
        subItems: [],
      },
    ],
  },
  {
    key: "2",
    id: 2,
    title: "Step 2",
    feeds: [3, 5],
    coords: [],
    subItems: [
      {
        key: "67",
        id: 6,
        title: "Step A",
        feeds: [2, 4],
        coords: [],
        subItems: [],
      },
      {
        key: "77",
        id: 7,
        title: "Step B",
        feeds: [2, 4],
        coords: [],
        subItems: [],
      },
    ],
  },
  {
    key: "3",
    id: 3,
    title: "Step 3",
    feeds: [4],
    coords: [],
    subItems: [],
  },
  {
    key: "4",
    id: 4,
    title: "Step 4",
    feeds: [5],
    coords: [],
    subItems: [],
  },
  {
    key: "5",
    id: 5,
    title: "Step 5",
    feeds: [],
    coords: [],
    subItems: [],
  },
];

export default items;
